# Auto-generated by sensitivitySweep.tcl — run 1 / 2
# Trap center: x=0.0 um  y=0.15000000000000002 um | type=Acceptor density=3e18 sigma=0.015

window row=2 col=3

# ── Trap parameters for this run ────────────────────────────────
set sens_mean_x  0.0
set sens_mean_y  0.15000000000000002
set sens_density 3e18
set sens_sigma   0.015
set sens_type    Acceptor
set sens_energy  3.1
set sens_width   0.025

# ── Load parameterized model and device geometry ─────────────────
source /home/staffian/banjo-wombat/allNit/sensitivityModelfile.tcl
source /home/staffian/banjo-wombat/allNit/fieldplate.tcl

# ── Load trapPlot proc ───────────────────────────────────────────
source /home/staffian/banjo-wombat/allNit/trapPlotProcs.tcl

# ── Run simulation ───────────────────────────────────────────────
trapPlot {/home/staffian/banjo-wombat/allNit/figures/sensitivity/iv_x0d0000_y0d1500.csv} 5.0 -2.0 2.6 0.018
